

services:
  data-generator:
    build:
      context: ./data-generator
      dockerfile: Dockerfile
    container_name: data-generator
    environment:
      - INGESTION_SVC_HOST=ingestion
      - INGESTION_SVC_PORT=5000
    develop:
      watch:
        - action: rebuild
          path: ./data-generator
  
  ingestion:
    build:
      context: ./ingestion
    container_name: ingestion
    hostname: ingestion
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: rebuild
          path: ./ingestion
    depends_on:
      kafka:
        condition: service_healthy


# Connect from within the docker network: kafka:9092
# Connect from outside (localhost): localhost:9094
  kafka:
    build:
      context: ./kafka-server
    container_name: kafka
    hostname: kafka
    ports:
      - "9094:9094"
      - "9092:9092"
    healthcheck:
      test: ['CMD-SHELL', 'kafka-topics.sh --bootstrap-server localhost:9092 --list | grep -q "market_data"']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  processing:
    build:
      context: ./processing
    container_name: processing
    depends_on:
      kafka:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./processing
    