apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-port-9092
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-port-9094
      protocol: TCP
      port: 9094
      targetPort: 9094
  type: ClusterIP
