apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingestion-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /ingestion
        pathType: Prefix
        backend:
          service:
            name: ingestion
            port:
              number: 5000