apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyze
  template:
    metadata:
      labels:
        app: analyze
    spec:
      containers:
        - name: analyze
          image: analyze:latest
          envFrom:
            - configMapRef:
                name: analyze
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: analyze
data:
  KAFKA__HOSTS: "kafka:9092"
  KAFKA__CONSUMER_GROUP: "analyze"

  POSTGRESQL__HOST: "data-postgresql"