apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyze
  template:
    metadata:
      labels:
        app: analyze
    spec:
      containers:
        - name: analyze
          image: analyze:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: analyze
          env:
            - name: KAFKA_SERVER
              value: my-kafka:9092
            - name: KAFKA_TOPIC_NAME
              value: market_data
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: analyze
data:
  KAFKA__HOSTS: "kafka:9092"
  KAFKA__CONSUMER_GROUP: "analyze"

  POSTGRESQL__HOST: "data-postgresql"
  POSTGRESQL__PORT: "5432"
  POSTGRESQL__USERNAME: "postgres"
  POSTGRESQL__PASSWORD: "postgres"
  POSTGRESQL__DBNAME: "postgres"