apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing
  template:
    metadata:
      labels:
        app: processing
    spec:
      containers:
        - name: processing
          image: processing:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8585
          env:
            - name: KAFKA_SERVER
              value: my-kafka.default.svc.cluster.local:9092
            - name: KAFKA_TOPIC_NAME
              value: market_data

