apiVersion: v1
kind: Service
metadata:
  name: processing
spec:
  selector:
    app: processing
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30585
  type: NodePort
