apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: ingestion:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_SERVER
              value: my-kafka:9092
            - name: KAFKA_TOPIC_NAME
              value: market_data

