[project]
name = "data-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.1",
    "psutil>=6.1.1",
    "requests>=2.32.3",
]
